{{- $namespace := default .Release.Namespace .Values.app-template.namespaceOverride -}}
{{- $config := .Files.Get "files/config.yml" | default "" -}}
{{- if not $config }}
{{- fail "files/config.yml must be present with Frigate configuration" }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  config.yml: |
{{ $config | indent 4 }}
