---
- name: Restart Prometheus
  become: true
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Restart Alertmanager
  become: true
  ansible.builtin.service:
    name: alertmanager
    state: restarted
